



sintx --ntasks=1 --account=compsci --partition=ada
conda activate EEGPT_env

module load python/miniconda3-py3.9
source activate /home/chntzi001/.conda/envs/EEGPT_env

pip install pyhealth

/scratch/chntzi001/TUAB/processed

To install PyHealth version 1.1.4:
git clone --branch v1.1.4 https://github.com/sunlabuiuc/PyHealth.git
cd PyHealth
pip install .

check if running an interactive job:
squeue -u $USER



accessing tensorboard log:

conda activate EEGPT_env
tensorboard --logdir=~/deepEEG/log/finetune_khula_eegpt --port=6006

in local terminal: ssh -L 6006:localhost:6006 chntzi001@srvrochpc001



  1_191_35197624_3_20220726_020636004_processed.set                           



test_sub_src: /scratch/chntzi001/khula/24M/1_191_38017803_24_20240129_110020002_processed.set, match.group(1): 24
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/chntzi001/.conda/envs/EEGPT_env/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/chntzi001/.conda/envs/EEGPT_env/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/chntzi001/deepEEG/make_khula.py", line 69, in split_and_dump
    for file in os.listdir(fetch_file):
NotADirectoryError: [Errno 20] Not a directory: '/scratch/chntzi001/khula/12M/1_191_37553535_12_20230821_015704002_processed.set'
"""
/                                                 scratch/chntzi001/khula/12M
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chntzi001/deepEEG/make_khula.py", line 317, in <module>
    result = pool.map(split_and_dump, parameters)
  File "/home/chntzi001/.conda/envs/EEGPT_env/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/chntzi001/.conda/envs/EEGPT_env/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
NotADirectoryError: [Errno 20] Not a directory: '/scratch/chntzi001/khula/12M/1_191_37553535_12_20230821_015704002_processed.set'

1_191_24503296_3_20220813_104317002_processed.set

FileNotFoundError: [Errno 2] No such file or directory: '/scratch/chntzi001/khula/train/1_191_19175800_6_20230216_092411002_processed_0.pkl'


⚠️ Skipping non-epoched file: /scratch/chntzi001/khula/12M/1_191_43759364_12_T_20230719_105955002_processed.set
⚠️ Skipping non-epoched file: /scratch/chntzi001/khula/12M/1_191_58011621_12_20230823_013452002_processed.set
❌ Cannot read file (corrupt?): /scratch/chntzi001/khula/24M/1_191_47621245_24_20240201_125136002_processed.set
  → Error: could not read bytes
❌ Cannot read file (corrupt?): /scratch/chntzi001/khula/3M/1_191_47621245_3_20220816_113421002_processed.set
  → Error: could not read bytes
❌ Cannot read file (corrupt?): /scratch/chntzi001/khula/6M/1_191_23150844_6_20230131_020106002_processed.set
  → Error: could not read bytes
❌ Cannot read file (corrupt?): /scratch/chntzi001/khula/6M/1_191_23603310_6_20230405_113844002_processed.set
  → Error: could not read bytes
❌ Cannot read file (corrupt?): /scratch/chntzi001/khula/6M/1_191_28039912_6_20230111_011331002_processed.set
  → Error: could not read bytes
❌ Cannot read file (corrupt?): /scratch/chntzi001/khula/6M/1_191_28097536_6_S_20221206_020230002_processed.set
  → Error: could not read bytes
❌ Cannot read file (corrupt?): /scratch/chntzi001/khula/6M/1_191_37298891_6_20230308_092006002_processed.set
  → Error: could not read bytes
⚠️ Skipping non-epoched file: /scratch/chntzi001/khula/6M/1_191_59659447_6_20230330_013531002_processed.set
❌ Cannot read file (corrupt?): /scratch/chntzi001/khula/6M/1_191_70439269_6_20230119_112718002_processed.set
  → Error: could not read bytes
                                